version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    stop_grace_period: 0s

  db:
    image: postgres:alpine
    restart: unless-stopped
    network_mode: service:app
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
