services:
  app:
    build:
      context: .
    stop_grace_period: 0s

  cargo:
    build:
      context: .
      target: dev
    depends_on:
      - postgres
    profiles:
      - cargo
    entrypoint: cargo
    environment:
      CARGO_HOME: $PWD/.cargo_home
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
